### ISSUE TITLE
Got red images

### ISSUE THREAD

**Issue by cnieves1** [hmt1203/doc88-download#1]
Dear all,
I tried this program, and I got png images, but all of them were completely filled with red color. 
I used:
  doc88-download <url begin with http://>
Size of each png image is about 61K.

Anything I can do to get this program working?
Thanks,

Carlos

**Comment by hmt1203** [comment]
Hello, 
It seems that the pepper flash player is not loaded correctly. This package comes with the plugins for Windows and Linux. If your system has Google Chrome installed and flash is working then you can try to locate "pepflashplayer.dll" (assume Windows) in your system and load with switch "--plugin-flash-path <path-to-pepflashplayer.dll>".

**Comment by cnieves1** [comment]
Hi,
Thanks for the hint!. Now it is working fine!.

For the records, I was using Ubuntu Trusty. The command line I needed was:
  doc88-downloader --plugin-flash-path
/usr/lib/pepperflashplugin-nonfree/libpepflashplayer.so
<url-begin-with-http://>
When I run again the program, I get one red-filled image with the text
"96%" at the center. It seems it didn't get enough time to download.
I deleted the image, run the program again, and the image was fine.

Thanks a lot for the program!

Carlos

2016-12-14 15:16 GMT+01:00 TunG <notifications@github.com>:

**Comment by cnieves1** [comment]
Hi again,
I have one suggestion that maybe its easy to add.

After downloading the images, I wanted a PDF file with all the images, so I
run, in a terminal:
  mkdir pdf
  for file in png/*; do convert $file pdf/`basename $file`.pdf;done
  pdftk pdf/*.pdf output full.pdf

Could you please add this to the program?

Thanks,

Carlos

2016-12-15 9:03 GMT+01:00 Carlos Nieves <cnieves.mail@gmail.com>:

**Comment by hmt1203** [comment]
Thank you for your suggestion and I am also looking for a solution which is free and cross platform for converting PNG image to PDF. I may add this feature in later version. Thanks.

**Comment by cnieves1** [comment]
I am playing with Tesseract, an ocr.
It is quite interesting to have a searchable PDF.

Regards,

Carlos
